-- 방법 1 윈도우 함수 이용
SELECT T1.ID, T2.FISH_NAME, T1.MAX_LENGTH AS LENGTH
FROM
    (SELECT ID, FISH_TYPE, MAX(LENGTH) OVER(PARTITION BY FISH_TYPE) AS MAX_LENGTH, LENGTH
     FROM FISH_INFO) T1 JOIN FISH_NAME_INFO T2
ON T1.FISH_TYPE = T2.FISH_TYPE
WHERE T1.MAX_LENGTH = T1.LENGTH
ORDER BY ID;

-- 방법 2 IN 사용
SELECT ID, FISH_NAME, LENGTH
FROM FISH_INFO JOIN FISH_NAME_INFO USING (FISH_TYPE)
WHERE (FISH_TYPE, LENGTH) IN (SELECT FISH_TYPE, MAX(LENGTH) AS LENGTH
                             FROM FISH_INFO
                             GROUP BY FISH_TYPE)
ORDER BY ID ASC;