SELECT COUNT(*) AS FISH_COUNT
FROM FISH_INFO JOIN FISH_NAME_INFO -- 기본 JOIN은 INNER JOIN으로 교집합 결과와 동일함
ON FISH_INFO.FISH_TYPE = FISH_NAME_INFO.FISH_TYPE
WHERE FISH_NAME = "BASS" OR FISH_NAME = "SNAPPER";