SELECT ID,
    CASE WHEN PERCENTAGE  <= 25 THEN 'CRITICAL' -- 상위 0~25%
         WHEN PERCENTAGE <= 50 THEN 'HIGH' -- 상위 26~50%
         WHEN PERCENTAGE <= 75 THEN 'MEDIUM' -- 상위 51~75%
         ELSE  'LOW' -- 상위 76~100%
    END
    AS COLONY_NAME
FROM (SELECT ID, RANK() OVER (ORDER BY SIZE_OF_COLONY DESC) / COUNT(*) OVER() * 100 AS PERCENTAGE
      FROM ECOLI_DATA) AS SUBQUERY -- ** 서브쿼리 활용
ORDER BY ID;