-- 윈도우 함수 이용
SELECT MONTH(START_DATE) AS MONTH, CAR_ID, COUNT(*) AS RECORDS
FROM (SELECT *, COUNT(*) OVER(PARTITION BY CAR_ID) AS COUNT_FOR_CAR_ID, COUNT(*) OVER(PARTITION BY MONTH(START_DATE)) AS COUNT_FOR_MONTH
      FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
      WHERE YEAR(START_DATE) = 2022 && (MONTH(START_DATE)>=8 && MONTH(START_DATE)<=10)) T
WHERE T.COUNT_FOR_CAR_ID >= 5 && T.COUNT_FOR_MONTH > 0
GROUP BY MONTH, CAR_ID
ORDER BY MONTH ASC, CAR_ID DESC;

-- IN 절 이용
SELECT MONTH(START_DATE) AS MONTH, CAR_ID, COUNT(CAR_ID) AS RECORDS
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
WHERE MONTH(START_DATE) BETWEEN 8 AND 10 AND
      CAR_ID IN (
          SELECT CAR_ID
          FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
          WHERE MONTH(START_DATE) BETWEEN 8 AND 10
          GROUP BY CAR_ID
          HAVING COUNT(CAR_ID) >= 5
      )
GROUP BY MONTH(START_DATE), CAR_ID
ORDER BY MONTH(START_DATE) ASC, CAR_ID DESC;