-- 재귀 함수 사용
WITH RECURSIVE CTE AS (
    SELECT ID, PARENT_ID, 1 AS DEPTH
    FROM ECOLI_DATA
    WHERE PARENT_ID IS NULL

    UNION ALL

    SELECT T1.ID, T1.PARENT_ID, (T2.DEPTH + 1) AS DEPTH
    FROM ECOLI_DATA T1 JOIN CTE T2
    ON T1.PARENT_ID = T2.ID
) -- ;로 쿼리를 끝내기 전까지 유효

SELECT ID
FROM CTE
WHERE DEPTH = 3
ORDER BY ID;

-- JOIN을 사용한 풀이
SELECT A.ID
FROM ECOLI_DATA AS A
JOIN ECOLI_DATA AS B ON A.PARENT_ID = B.ID
JOIN ECOLI_DATA AS C ON B.PARENT_ID = C.ID
WHERE C.PARENT_ID IS NULL
ORDER BY A.ID ASC;
