SELECT COUNT(*) AS FISH_COUNT, IFNULL(MAX(LENGTH), 10) AS MAX_LENGTH, FISH_TYPE
FROM FISH_INFO
GROUP BY FISH_TYPE
HAVING AVG(IFNULL(LENGTH, 10)) >= 33 -- IFNULL로 10cm 이하의 물고기 길이는 10cm로 계산하도록 하기
ORDER BY FISH_TYPE;